import type { Metadata } from 'next';
import './globals.css';

import { Appwrapper } from '@/providers/ContextAppProvider';
import Navbar from '@/component/Navbar/navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <Navbar />
        <Appwrapper>{children}</Appwrapper>
      </body>
    </html>
  );
}
